version: '3.0'

expectations:
  population_size: 1000

actions:

  
  generate_study_population_conscious_level_blood_pressure:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=altered_conscious_level,blood_pressure
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_clinical_concern_dehydration:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=causing_clinical_concern,dehydration_or_shock
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  generate_study_population_heart_rate_resp_rate:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=heart_rate,respiratory_rate
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv.gz

  generate_study_population_ox_temp:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=oxygen_saturation,temperature
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv.gz

  generate_study_population_who_dem:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=who_performance_score,demographic_variables
    outputs:
      highly_sensitive:
        cohort: output/in*.csv.gz

  generate_study_population_resp:
    run: >
      cohortextractor:latest generate_cohort
      --study-definition study_definition_v2
      --index-date-range "2020-03-01 to 2021-06-01 by month"
      --output-format=csv.gz
      --with-end-date-fix
      --param varset=severe_respiratory_distress,respiratory_exhaustion
    outputs:
      highly_sensitive:
        cohort: output/i*.csv.gz


  generate_study_population_end:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_end --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input_end.csv.gz

  
  join_cohorts_monthly:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_v2*.csv.gz
        --rhs output/input_end.csv.gz
        --output-dir output/joined
    needs: [
      generate_study_population_conscious_level_blood_pressure,
      generate_study_population_clinical_concern_dehydration,
      generate_study_population_heart_rate_resp_rate,
      generate_study_population_ox_temp,
      generate_study_population_who_dem,
      generate_study_population_resp,
      generate_study_population_end
      ]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz



  # combined_input_files:
  #   run: python:latest python analysis/combine_input_files.py
  #   needs: [join_cohorts_monthly]
  #   outputs:
  #     highly_sensitive:
  #       attrition: output/joined/input_all_py.csv.gz

  # column_counts:
  #   run: python:latest python analysis/test_column_counts.py
  #   needs: [generate_study_population_v2_conscious_level]
  #   outputs:
  #     moderately_sensitive:
  #       counts: output/column_counts/*.csv

  # generate_first_outputs:
  #   run: r:latest analysis/flucats_descriptive_basic.R
  #   needs: [combined_input_files]
  #   outputs:
  #     moderately_sensitive:
  #       attrition: output/attrition.csv
  #       histogram_age: output/age_hist.png
  #       date_plot: output/weekly_template.png
  #       flucat_tables: output/flucat*.csv
  #       sex_table: output/sex_table.csv
  #       region_table: output/region_table.csv


  