version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01 to 2021-03-07 by week" --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  # Gives until 2021-06-27
  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-03-14 to 2021-06-20 by week" --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  # gives until 2022-03-27. Only have ONS deaths until 2021-07-01
  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-06-27 to 2022-03-20 by week" --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv.gz
  

  generate_study_population_end:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_end --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input_end.csv.gz

  join_cohorts_weekly:
    run: >
      cohort-joiner:v0.0.44
        --lhs output/input_20*.csv.gz
        --rhs output/input_end.csv.gz
        --output-dir output/joined
    needs: [
      generate_study_population_1,
      generate_study_population_2,
      generate_study_population_end]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_20*.csv.gz


  generate_dataset_report:
    run: >
      dataset-report:v0.0.24
        --input-files output/joined/input_2022-03-20.csv.gz
        --output-dir output/joined
    needs: [join_cohorts_weekly]
    outputs:
      moderately_sensitive:
        dataset_report: output/joined/input_2022-03-20.html

