version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_test:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_test --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input_test.csv.gz
  
  column_counts:
    run: python:latest python analysis/test_column_counts.py
    needs: [generate_study_population_test, combined_input_files, generate_study_population_2]
    outputs:
      moderately_sensitive:
        counts: output/column_counts/combine*.csv
   
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01 to 2020-07-01 by month" --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-08-01 to 2021-01-01 by month" --output-format=csv.gz --with-end-date-fix
    outputs:
      highly_sensitive:
        cohort: output/input*.csv.gz

  # Gives until 2021-07-01. Only have ONS deaths until 2021-07-01
  # generate_study_population_3:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-02-01 to 2021-06-01 by month" --output-format=csv.gz --with-end-date-fix
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/inpu*.csv.gz
  

  # generate_study_population_end:
  #   run: cohortextractor:latest generate_cohort --study-definition study_definition_end --output-format=csv.gz --with-end-date-fix
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_end.csv.gz

  # join_cohorts_monthly:
  #   run: >
  #     cohort-joiner:v0.0.44
  #       --lhs output/input_20*.csv.gz
  #       --rhs output/input_end.csv.gz
  #       --output-dir output/joined
  #   needs: [
  #     generate_study_population_1,
  #     generate_study_population_2,
  #     generate_study_population_3,
  #     generate_study_population_end]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/joined/input_20*.csv.gz


  generate_dataset_report:
    run: >
      dataset-report:v0.0.24
        --input-files output/input_2021-01-01.csv.gz
        --output-dir output
    needs: [generate_study_population_2]
    outputs:
      moderately_sensitive:
        dataset_report: output/input_2021-01-01.html

  combined_input_files:
    run: r:latest analysis/combine_input_files.R


    needs: [generate_study_population_1, generate_study_population_2]
    outputs:
      highly_sensitive:
        attrition: output/input_all.csv.gz
  
  combined_input_files_py:
    run: python:latest python analysis/combine_input_files.py
    needs: [generate_study_population_1, generate_study_population_2]
    outputs:
      highly_sensitive:
        attrition: output/input_all_py.csv.gz


  generate_first_outputs:
    run: r:latest analysis/flucats_descriptive_basic.R


    needs: [combined_input_files]
    outputs:
      moderately_sensitive:
        attrition: output/attrition.csv
        histogram_age: output/age_hist.png
        date_plot: output/weekly_template.png
        flucat_tables: output/flucat*.csv
        sex_table: output/sex_table.csv
        region_table: output/region_table.csv

  # check_codes:
  #   run: r:latest analysis/check_codes.R
  #   needs: [generate_study_population_2]
  #   outputs:
  #     moderately_sensitive:
  #       text: output/text.txt

