---
name: CI

on:
  merge_group:
  pull_request:
  push:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
          install-just: true
      - name: Install venv
        run: just devenv
      - name: Run tests
        run: |
          just test
